# Generated by Django 4.1.7 on 2023-03-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.category'),
        ),
    ]
